data = """
	SIZ		64		NONE		HIGH		NO		NO
	SIO		65		SINGLE		LOW		NO		NO
	SAO		66		SINGLE		LOW		NO		NO
	SIPO		67		SINGLE		LOW		NO		NO
	SIPZ		68		SINGLE		LOW		NO		NO
	SIB		69		SINGLE		HIGH		NO		NO
	SIR		70		SINGLE		LOW		NO		NO
	SIV		71		NONE		HIGH		NO		NO
	RRM		72		NONE		LOW		NO		NO
	RRMO		73		NONE		LOW		NO		NO
	OCP		74		NONE		HIGH		NO		NO
	OCO		75		NONE		LOW		NO		NO
	ONP		76		NONE		HIGH		NO		NO
	ONO		77		NONE		LOW		NO		NO
	STP		80		SINGLE		LOW		NO		NO
	STM		81		SINGLE		LOW		NO		NO
	STPZ		82		SINGLE		LOW		NO		NO
	STMZ		83		SINGLE		LOW		NO		NO
	STB		84		SINGLE		HIGH		NO		NO
	STR		85		SINGLE		LOW		NO		NO
	STL		93		NONE		LOW		NO		NO
	STC		94		NONE		LOW		NO		NO
	STEC		95		NONE		LOW		NO		NO
	SEIR		96		SINGLE		LOW		NO		NO
	SEB		97		SINGLE		HIGH		NO		NO
	SER		98		SINGLE		LOW		NO		NO
	SEL		99		SINGLE		LOW		NO		NO
	SEO		100		SINGLE		LOW		NO		NO
	SEZ		101		SINGLE		LOW		NO		NO
	SEOG		102		NONE		LOW		NO		NO
	UPM		112		SINGLE		LOW		YES		NO
	UMM		113		SINGLE		LOW		YES		NO
	UPB		114		SINGLE		LOW		YES		NO
	UMB		115		SINGLE		LOW		YES		NO
	UMD		116		SINGLE		LOW		YES		NO
	OM		117		SINGLE		HIGH		NO		NO
	UPS		118		SINGLE		LOW		YES		NO
	UMS		119		SINGLE		LOW		YES		NO
	ABO		128		SINGLE		LOW		NO		NO
	ABS		129		SINGLE		LOW		NO		NO
	ABVO		130		SINGLE		HIGH		NO 		NO
	ABVP		131		SINGLE		HIGH		NO 		NO
	PZP		144		SINGLE		HIGH		NO		NO
	PZO		145		SINGLE		LOW		NO		NO
	PPI		146		SINGLE		LOW		NO		NO
	PSI		147		SINGLE		LOW		NO		NO
	SAZ		148		SINGLE		LOW		NO		NO
	COO		160		NONE		LOW		NO		NO
	COV1		161		NONE		LOW		NO		NO
	COV2		162		NONE		LOW		NO		NO
	COV3		163		NONE		LOW		NO		NO
	COI		164		NONE		LOW		NO		NO
	COIC		178		NONE		LOW		NO		NO
	POK		165		NONE		LOW		NO		NO
	VKL		176		NONE		LOW		NO		NO
	OTKL		177		NONE		LOW		NO		NO
	COM0		180		SINGLE		LOW		NO		NO
	COM1		181		SINGLE		LOW		NO		NO
	COM2		182		NONE		LOW		NO		NO
	COM3		183		NONE		LOW		NO		NO
	COM4		184		SINGLE		LOW		NO		NO
	COM5		185		SINGLE		LOW		NO		NO
	COM6		186		NONE		LOW		NO		NO
	COM7		187		SINGLE		LOW		NO		NO
	COM8		188		SINGLE		LOW		NO		NO
	COM9		189		SINGLE		LOW		NO		NO
	COM10		190		NONE		HIGH		NO		NO
	COM11		191		NONE		HIGH		NO		NO
	COM12		192		NONE		HIGH		NO		NO
	COM13		193		NONE		HIGH		NO		NO
	COM14		194		NONE		HIGH		NO		NO
	COM15		195		NONE		HIGH		NO		NO
	COM16		196		NONE		HIGH		NO		NO
	COM17		197		NONE		HIGH		NO		NO
	COM18		198		NONE		HIGH		NO		NO
	COM19		199		NONE		HIGH		NO		NO
	SU2		200		SINGLE		LOW		NO		NO
	SU		201		SINGLE		LOW		NO		NO
	OSU		202		SINGLE		LOW		NO		NO
	VSU		203		SINGLE		LOW		NO		NO
	OVSU		204		SINGLE		LOW		NO		NO
	RUZ		205		SINGLE		LOW		NO		NO
	ORUZ		206		SINGLE		LOW		NO		NO
	SLZ		207		SINGLE		LOW		NO		NO
	OPL		208		SINGLE		LOW		NO		NO
	OOPL		209		SINGLE		LOW		NO		NO
	RO		210		SINGLE		LOW		NO		NO
	ORO		211		SINGLE		LOW		NO		NO
	OHP		212		SINGLE		LOW		NO		NO
	DSO		213		NONE		LOW		NO		NO
	OSO		214		NONE		LOW		NO		NO
	DP		215		NONE		LOW		NO		NO
	IFP		216		NONE		LOW		NO		NO
	BO		217		SINGLE		HIGH		NO		NO
	OBO		218		SINGLE		LOW		NO		NO
	GRI		219		SINGLE		LOW		NO		NO
	SIIP		220		NONE		LOW		NO		NO
	GV		221		SINGLE		LOW		NO		NO
	OGV		222		SINGLE		LOW		NO		NO
	RMU		223		SINGLE		LOW		NO		NO
	ORMU		224		SINGLE		LOW		NO		NO
	VSU2		225		SINGLE		LOW		NO		NO
	SEVP		226		SINGLE		LOW		NO		NO
	OSEVP		227		SINGLE		LOW		NO		NO
	SEVFEU		228		SINGLE		LOW		NO		NO
	OSEVFEU		229		SINGLE		LOW		NO		NO
	SEV		230		SINGLE		LOW		NO		NO
	OSEV		231		SINGLE		LOW		NO		NO
	OVSU2		232		SINGLE		LOW		NO		NO
	SU_ARM		233		SINGLE		LOW		NO		NO
	OSU_ARM		234		SINGLE		LOW		NO		NO
	VSU_ARM		235		SINGLE		LOW		NO		NO
	OVSU_ARM	236		SINGLE		LOW		NO		NO

"""

data = data.strip()

for line in data.split('\n'):
    s1,s2,s3,s4,s5,s6 = line.split()
    p1 = len('COS1_COM_NOT_OK')
    p2 = len('Eventcode  ')
    p3 = len('Pretest    ')
    p4 = len('Priority   ')
    p5 = len('Pretest ind.   ')
    p6 = len('Vital comm  ')
    print(f"    {s1:{p1}} {s2:{p2}} {s3:{p3}} {s4:{p4}} {s5:{p5}} {s6:{p6}}")
